/****** Object:  Table [dbo].[temp_old1409]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[temp_old1409](
	[ReportDate] [nvarchar](50) NULL,
	[RecordID] [nvarchar](20) NULL,
	[CreatedBy] [nvarchar](50) NULL,
	[CreatedTime] [nvarchar](50) NULL,
	[UpdatedBy] [nvarchar](50) NULL,
	[UpdatedTime] [nvarchar](50) NULL,
	[AccountGroup (selectsource-2)] [nvarchar](4000) NULL,
	[ParentGroup (selectsource-3)] [nvarchar](4000) NULL,
	[AccountType (selectsource-7)] [nvarchar](4000) NULL,
	[ALGOIndicator (selectbasic-26)] [nvarchar](4000) NULL,
	[CustomerID (selectsource-1)] [nvarchar](4000) NULL,
	[AccountNumber (textinput-5)] [nvarchar](4000) NULL,
	[AccountSubCode (textinput-6)] [nvarchar](4000) NULL,
	[NomineesName1 (selectsource-20)] [nvarchar](4000) NULL,
	[NomineesName2 (textinput-7)] [nvarchar](4000) NULL,
	[NomineesName3 (textinput-8)] [nvarchar](4000) NULL,
	[NomineesName4 (textinput-9)] [nvarchar](4000) NULL,
	[AbbreviatedName (textinput-10)] [nvarchar](4000) NULL,
	[CADEntityType1 (selectsource-18)] [nvarchar](4000) NULL,
	[AveragingOption (multipleradiosinline-1)] [nvarchar](4000) NULL,
	[OddLotAveragingOption (selectbasic-4)] [nvarchar](4000) NULL,
	[DealerCode (selectsource-21)] [nvarchar](4000) NULL,
	[SendClientInfotoBFE (selectbasic-27)] [nvarchar](4000) NULL,
	[AccountStatus (selectsource-9)] [nvarchar](4000) NULL,
	[MRIndicator (multipleradiosinline-4)] [nvarchar](4000) NULL,
	[MRReference (selectsource-22)] [nvarchar](4000) NULL,
	[ReferenceSource (selectsource-23)] [nvarchar](4000) NULL,
	[CDSNo (textinput-19)] [nvarchar](4000) NULL,
	[CDSACOpenBranch (selectsource-4)] [nvarchar](4000) NULL,
	[NomineeInd (selectsource-5)] [nvarchar](4000) NULL,
	[StructureWarrant (selectbasic-7)] [nvarchar](4000) NULL,
	[ShortSellInd (selectsource-19)] [nvarchar](4000) NULL,
	[IDSSInd (multipleradiosinline-10)] [nvarchar](4000) NULL,
	[PSSInd (multipleradiosinline-11)] [nvarchar](4000) NULL,
	[IslamicTradeInd (selectbasic-9)] [nvarchar](4000) NULL,
	[IntraDayInd (selectbasic-12)] [nvarchar](4000) NULL,
	[SettlementCurrency (selectsource-6)] [nvarchar](4000) NULL,
	[ContraInd (selectbasic-13)] [nvarchar](4000) NULL,
	[ContraforShortSelling (selectbasic-28)] [nvarchar](4000) NULL,
	[ContraforOddLots (selectbasic-15)] [nvarchar](4000) NULL,
	[ContraforIntraday (selectbasic-29)] [nvarchar](4000) NULL,
	[DesignatedCounterInd (selectbasic-16)] [nvarchar](4000) NULL,
	[ImmediateBasisInd (selectbasic-19)] [nvarchar](4000) NULL,
	[SetoffInd (selectbasic-30)] [nvarchar](4000) NULL,
	[SetoffContraGainDebitAmount (selectbasic-31)] [nvarchar](4000) NULL,
	[SetoffSalesPurchasesReport (selectbasic-32)] [nvarchar](4000) NULL,
	[SetoffTrustDebitTransactions (selectbasic-33)] [nvarchar](4000) NULL,
	[SetoffTrustContraLoss (selectbasic-34)] [nvarchar](4000) NULL,
	[TransferCreditTransactiontoTrust (selectbasic-35)] [nvarchar](4000) NULL,
	[UserID (textinput-52)] [nvarchar](4000) NULL,
	[OnlineSystemIndicator (multiplecheckboxesinline-1)] [nvarchar](4000) NULL,
	[VBIP (selectbasic-39)] [nvarchar](4000) NULL,
	[WithLimit (multipleradiosinline-18)] [nvarchar](4000) NULL,
	[ClearPreviousDayOrder (multipleradiosinline-19)] [nvarchar](4000) NULL,
	[Access (multipleradiosinline-20)] [nvarchar](4000) NULL,
	[Buy (multipleradiosinline-21)] [nvarchar](4000) NULL,
	[Sell (multipleradiosinline-22)] [nvarchar](4000) NULL,
	[SuspensionReason (selectsource-30)] [nvarchar](4000) NULL,
	[Remarks (textinput-72)] [nvarchar](4000) NULL,
	[MaxBuyLimit (textinput-68)] [nvarchar](4000) NULL,
	[MaxSellLimit (textinput-69)] [nvarchar](4000) NULL,
	[MaxNetLimit (textinput-70)] [nvarchar](4000) NULL,
	[ExceedLimit (textinput-71)] [nvarchar](4000) NULL,
	[ApproveTradingLimit (textinput-54)] [nvarchar](4000) NULL,
	[AvailableTradingLimit (textinput-55)] [nvarchar](4000) NULL,
	[BFEACType (selectsource-29)] [nvarchar](4000) NULL,
	[ClientAssoallowed (multipleradiosinline-13)] [nvarchar](4000) NULL,
	[ClientReassignallowed (multipleradiosinline-14)] [nvarchar](4000) NULL,
	[ClientCrossamend (multipleradiosinline-15)] [nvarchar](4000) NULL,
	[MultiplierforCashDeposit (textinput-56)] [nvarchar](4000) NULL,
	[MultiplierforSharePledged (textinput-57)] [nvarchar](4000) NULL,
	[MultiplierforNonShare (textinput-58)] [nvarchar](4000) NULL,
	[AvailableCleanLineLimit (textinput-59)] [nvarchar](4000) NULL,
	[StartDate (dateinput-9)] [nvarchar](4000) NULL,
	[EndDate (dateinput-10)] [nvarchar](4000) NULL,
	[TemporaryLimit (textinput-60)] [nvarchar](4000) NULL,
	[StartDate (dateinput-11)] [nvarchar](4000) NULL,
	[EndDate (dateinput-12)] [nvarchar](4000) NULL,
	[LegalStatus (selectsource-24)] [nvarchar](4000) NULL,
	[BankruptcyorWindingupstatus (multipleradiosinline-12)] [nvarchar](4000) NULL,
	[BankruptcyorWindingupreason (textinput-61)] [nvarchar](4000) NULL,
	[DatedeclaredbankruptcyorWindingup (dateinput-13)] [nvarchar](4000) NULL,
	[DatedischargedbankruptcyorWindingup (dateinput-14)] [nvarchar](4000) NULL,
	[Remark1 (textinput-62)] [nvarchar](4000) NULL,
	[Remark2 (textinput-63)] [nvarchar](4000) NULL,
	[Financier (selectsource-25)] [nvarchar](4000) NULL,
	[MarginCode (textinput-39)] [nvarchar](4000) NULL,
	[CommencementDate (dateinput-4)] [nvarchar](4000) NULL,
	[ExclusionforAutoRenewal (selectbasic-40)] [nvarchar](4000) NULL,
	[TenorExpiryDate (dateinput-5)] [nvarchar](4000) NULL,
	[LetterofOfferdate (dateinput-15)] [nvarchar](4000) NULL,
	[FacilityAgreementDate (dateinput-16)] [nvarchar](4000) NULL,
	[MortgageAgreementDate (dateinput-17)] [nvarchar](4000) NULL,
	[ApprovedLimit (textinput-64)] [nvarchar](4000) NULL,
	[ApprovedMargin (textinput-65)] [nvarchar](4000) NULL,
	[ApprovedRSV (textinput-43)] [nvarchar](4000) NULL,
	[PriceCapMOF (textinput-44)] [nvarchar](4000) NULL,
	[MarginCallInterval (selectbasic-38)] [nvarchar](4000) NULL,
	[AuthorisedRepresentative (textinput-66)] [nvarchar](4000) NULL,
	[CurrentMargin (textinput-47)] [nvarchar](4000) NULL,
	[CurrentRSV (textinput-48)] [nvarchar](4000) NULL,
	[CommitmentFeeCode (selectsource-26)] [nvarchar](4000) NULL
) ON [PRIMARY]