/****** Object:  View [report].[Vw_AcctOpeningCFT910]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [report].[Vw_AcctOpeningCFT910]
AS 
SELECT [Status]
      ,[StatusRemarks]
	  ,[RecordType]
      ,[ParticiapantCode]
      ,[AcctNo]
      ,[AcctType]
      ,[NRICId]
      ,[OldNRICId]
      ,[ExistInvInd]
      ,[InvestorName]
      ,[InvestorType]
      ,[Nationality/POI] [NationalityPOI]
      ,[Race]
      ,[Address1]
      ,[Address2]
      ,[Town]
      ,[State]
      ,[PostalCode]
      ,[Country]
      ,[BeneficialOwner]
      ,[Qualifier1]
      ,[Qualifier2]
      ,[CorrAddress1]
      ,[CorrAddress2]
      ,[CorrTown]
      ,[CorrState]
      ,[CorrPostalCode]
      ,[CorrCountry]
      ,[PhoneIdd]
      ,[PhoneStd]
      ,[PhoneLocal]
      ,[PhoneExt]
      ,[AcctStatus]
      ,[BankAccount]
      ,[BankCode]
      ,[ConsolidateInd]
      ,[JointInd]
      ,[PhoneMobileIdd]
      ,[PhoneMobileCode]
      ,[PhoneMobileNo]
      ,[Email]
      ,[DateConsentEnd]
      ,[Remarks]
      ,[TaggingCode]
      ,[Filler]
  FROM [GlobalBOMY].[export].[Tb_BURSA_CFT910]