/****** Object:  Procedure [export].[USP_FRA_IFCUSTMAST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [export].[USP_FRA_IFCUSTMAST]
(
	@idteProcessDate DATE
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

   CREATE TABLE #IFCUSTMAST
   (
		CUSTKEY CHAR(10),
		COMPANYID CHAR(1),
		BRANCHID CHAR(4),
		EAFID CHAR(3),
		LGLSTAT CHAR(2),
		SUSPDREASN CHAR(4),
		BNKRUPTREA CHAR(4),
		RACECD CHAR(2),

		IDTYPECD CHAR(2),
		IDNUMBER CHAR(15),
		IDTYPECD1 CHAR(2),
		IDNUMBER1 CHAR(15),
		COUNTRYRES CHAR(3),
		COUNTRYNAT CHAR(3),
		CUSTFNAME CHAR(60),
		CUSTSNAM CHAR(20),
		CUSTTYPE CHAR(1),
		CUSTTITLE CHAR(20),
		RADDR1 CHAR(40),
		RADDR2 CHAR(40),
		RADDR3 CHAR(40),
		RADDR4 CHAR(40),
		RADDR5 CHAR(40),

		RPOSTCD CHAR(10),
		PHONE CHAR(15),
		PHONE1 CHAR(15),
		PHONE2 CHAR(15),
		FAX CHAR(15),
		TELEX CHAR(10),
		ELECADDR CHAR(20),
		DTBIRTH DATE,
		SEX CHAR(1),
		MARRSTAT CHAR(1),
		NOOFDEPD DECIMAL(2,0),
		YRINRESD DECIMAL(2,0),
		RESDOWN CHAR(1),
		ANNLINCOME DECIMAL(15,2),
		OTHINCOM DECIMAL(15,2),
		OTHINCRM CHAR(50),

		PRSTATUS CHAR(1),
		CONSTITUTN CHAR(3),
		DTINCORP DATE,
		AUTHCAP DECIMAL(15,2),
		AUTHCAPDT DATE,
		PAIDCAP DECIMAL(15,2),
		PAIDCAPDT DATE,
		RTEARN DECIMAL(15,2),
		RTEARNDT DATE,
		BIZNESSNAT CHAR(40),
		AUDITFRM CHAR(40),
		SIGNTREQ CHAR(50),
		REMARK1 CHAR(50),
		REMARK2 CHAR(50),

		BNKRUPTST CHAR(1),
		DTDCLBRPT DATE,
		DTDISBRPT DATE,
		LSTOFFSTAT CHAR(2),
		DTLSTOFFSH DATE,
		RMKOFFSH CHAR(50),
		BUMISTAT CHAR(1),
		FRNACHLDR CHAR(1),
		FILENMSIG CHAR(30),
		FILENMPIC CHAR(30),
		CREDITRTG CHAR(2),
		DIALECT CHAR(3),
		INCOME DECIMAL(14,2),
		OCCUPCD CHAR(4),

		SWIFTADD CHAR(15),
		ACCESSLVL CHAR(2),
		GRPPRFID CHAR(10),
		INTMETHOD CHAR(1),
		USRCREATED CHAR(10),
		DTCREATED DATE,
		TMCREATED CHAR(8),
		USRUPDATED CHAR(10),
		DTUPDATED DATE,
		TMUPDATED CHAR(8),
		RCDSTAT CHAR(1),
		RCDVERSION DECIMAL(5,0),
		PGMLSTUPD CHAR(10)

   )
   INSERT INTO #IFCUSTMAST
   (
		CUSTKEY,
		COMPANYID,
		BRANCHID,
		EAFID,
		LGLSTAT,
		SUSPDREASN,
		BNKRUPTREA,
		RACECD,
		IDTYPECD,
		IDNUMBER,
		IDTYPECD1,
		IDNUMBER1,
		COUNTRYRES,
		COUNTRYNAT,
		CUSTFNAME,
		CUSTSNAM,
		CUSTTYPE,
		CUSTTITLE,
		RADDR1,
		RADDR2,
		RADDR3,
		RADDR4,
		RADDR5,
		RPOSTCD,
		PHONE,
		PHONE1,
		PHONE2,
		FAX,
		TELEX,
		ELECADDR,
		DTBIRTH,
		SEX,
		MARRSTAT,
		NOOFDEPD,
		YRINRESD,
		RESDOWN,
		ANNLINCOME,
		OTHINCOM,
		OTHINCRM,
		PRSTATUS,
		CONSTITUTN,
		DTINCORP,
		AUTHCAP,
		AUTHCAPDT,
		PAIDCAP,
		PAIDCAPDT,
		RTEARN,
		RTEARNDT,
		BIZNESSNAT,
		AUDITFRM,
		SIGNTREQ,
		REMARK1,
		REMARK2,
		BNKRUPTST,
		DTDCLBRPT,
		DTDISBRPT,
		LSTOFFSTAT,
		DTLSTOFFSH,
		RMKOFFSH,
		BUMISTAT,
		FRNACHLDR,
		FILENMSIG,
		FILENMPIC,
		CREDITRTG,
		DIALECT,
		INCOME,
		OCCUPCD,
		SWIFTADD,
		ACCESSLVL,
		GRPPRFID,
		INTMETHOD,
		USRCREATED,
		DTCREATED,
		TMCREATED,
		USRUPDATED,
		DTUPDATED,
		TMUPDATED,
		RCDSTAT,
		RCDVERSION,
		PGMLSTUPD
   )
   SELECT
   
	   CUSTOMER.[CustomerID (textinput-1)],--CUSTKEY
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '', --10

	   '',
	   '',
	   '',
	   CUSTOMER.[Nationality (selectsource-4)], --COUNTRYNAT
	   '',
	   '',
	   '',
	   '',
	   '',
	   '', --20

	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '', --30

	   CUSTOMER.[DateofBirth (dateinput-1)],
	   '',
	   '',
	   '',
	   '',
	   '',
	   CUSTOMER.[GrossAnnualIncome (multipleradios-3)],
	   '',
	   '',
	   '', --40

	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   CUSTOMER.[BusinessNature (textinput-8)],
	   '', --50

	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '', --60

	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   CUSTOMER.[OccupationDesignation (textinput-162)],
	   '',
	   '',
	   '', --70

	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '' --80 --PGMLSTUPD

   FROM CQBTEMPDB.EXPORT.TB_FORMDATA_1410 CUSTOMER 


   --RESULT SET

   SELECT 
   CUSTKEY + COMPANYID + BRANCHID + EAFID + LGLSTAT + SUSPDREASN + BNKRUPTREA + RACECD + IDTYPECD + IDNUMBER + IDTYPECD1 +
		IDNUMBER1 + COUNTRYRES + COUNTRYNAT + CUSTFNAME + CUSTSNAM + CUSTTYPE + CUSTTITLE + RADDR1 + RADDR2 + RADDR3 +
		RADDR4 + RADDR5 + RPOSTCD + PHONE + PHONE1 + PHONE2 + FAX + TELEX + ELECADDR + DTBIRTH + SEX + MARRSTAT + CAST(NOOFDEPD AS CHAR(8)) +
		CAST(YRINRESD AS CHAR(8)) + RESDOWN + CAST(ANNLINCOME AS CHAR(8)) + CAST(OTHINCOM AS CHAR(8)) + OTHINCRM + PRSTATUS + CONSTITUTN + DTINCORP + CAST(AUTHCAP AS CHAR(8)) + AUTHCAPDT +
		CAST(PAIDCAP AS CHAR(8)) + PAIDCAPDT + CAST(RTEARN AS CHAR(8)) + RTEARNDT + BIZNESSNAT + AUDITFRM + SIGNTREQ + REMARK1 + REMARK2 + BNKRUPTST + DTDCLBRPT +
		DTDISBRPT + LSTOFFSTAT + DTLSTOFFSH + RMKOFFSH + BUMISTAT + FRNACHLDR + FILENMSIG + FILENMPIC + CREDITRTG + DIALECT +
		CAST(INCOME AS CHAR(8)) + OCCUPCD + SWIFTADD + ACCESSLVL + GRPPRFID + INTMETHOD + USRCREATED + DTCREATED + TMCREATED + USRUPDATED +
		DTUPDATED + TMUPDATED + RCDSTAT + CAST(RCDVERSION AS CHAR(8)) + PGMLSTUPD
		FROM #IFCUSTMAST
END