/****** Object:  Procedure [export].[USP_FRA_IFCLIENT]    Committed by VersionSQL https://www.versionsql.com ******/

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [export].[USP_FRA_IFCLIENT] 
(
	@idteProcessDate DATE
)
AS
BEGIN

	SET NOCOUNT ON;
	CREATE TABLE #IFCLIENT
	(
		COMPANYID CHAR(1),
		BRANCHID CHAR(4),
		EAFID CHAR(3),
		ACCTNO CHAR(10),
		ACCTSBNO CHAR(4),
		ACCTGRPCD CHAR(5),
		ACCTTYPECD CHAR(2),
		OFFICERCD CHAR(10),
		SUSPDREASN CHAR(4),
		CLOSEREASN CHAR(4),
		ACCLASSCD CHAR(10),
		CORRMTHD CHAR(1),
		FINANCECD CHAR(10),
		LGLSTAT CHAR(2),
		ACCTFNAME CHAR(60),
		ACCTSNAME CHAR(20),
		CORRADDR1 CHAR(40),
		CORRADDR2 CHAR(40),
		CORRADDR3 CHAR(40),
		CORRADDR4 CHAR(40),
		CORRADDR5 CHAR(40),
		CORRNAME CHAR(40),
		CORRTITLE CHAR(20),
		CORRPOSTCD CHAR(10),
		FORADDR CHAR(1),
		PHONE CHAR(15),
		PHONE1 CHAR(15),
		PHONE2 CHAR(15),
		FAX CHAR(15),
		ELECADDR CHAR(20),
		ACCTSTAT CHAR(2),
		DTACCTOPEN DATE,
		DTSUSPND DATE,
		DTCLOSED DATE,
		USROPENED CHAR(10),
		USRSUSPND CHAR(10),
		USRCLOSED CHAR(10),
		FRNACHLDR CHAR(1),
		JNTACHLDR CHAR(1),
		REMARK1 CHAR(50),
		REMARK2 CHAR(50),
		CUSTTYPE CHAR(1),
		BUMISTAT CHAR(1),
		LSTTRXDT DATE,
		LSTTRDDT DATE,
		BNKRUPTST CHAR(1),
		PRTSTMT CHAR(1),
		DTPRTSTMT DATE,
		DTSTMTPRTD DATE,
		USRCREATED CHAR(10),
		DTCREATED DATE,
		TMCREATED CHAR(8),
		USRUPDATED CHAR(10),
		DTUPDATED DATE,
		TMUPDATED CHAR(8),
		RCDSTAT CHAR(1),
		RCDVERSION DECIMAL(5,0),
		PGMLSTUPD CHAR(10),
		TRIGGERACT CHAR(1),
		USRAPPROVE CHAR(10),
		DTAPPROVED DATE,
		TMAPPROVED CHAR(8),
		SERIALNMBR DECIMAL(11,0),
		ACTITLE CHAR(20),
		SETTMODECD CHAR(2),
		SETTCURR CHAR(3),
		SETTBANK CHAR(50),
		SETTBANKAC CHAR(20),
		SETTACCTNM CHAR(60),
		ACCESSLVL CHAR(2),
		CRDRANKCD CHAR(2),
		GRPPRFID CHAR(10),
		ACCTUSECD CHAR(3),
		ANALCD1 CHAR(10),
		ANALCD2 CHAR(10),
		ANALCD3 CHAR(10),
		SWIFTADD CHAR(15),
		RELACCTNO CHAR(20),
		CUSTKEY CHAR(10),
		APPFORM CHAR(3),
		AUTOPAYAPP CHAR(1),
		AUTORECAPP CHAR(1),
		ISLFINANCD CHAR(10),
		INETMAIL CHAR(50),
		DCORRADDR1 CHAR(40),
		DCORRADDR2 CHAR(40),
		DCORRADDR3 CHAR(40),
		DCORRADDR4 CHAR(40),
		DCORRADDR5 CHAR(40),
		DCORRNAME CHAR(40),
		DCORRTITLE CHAR(20),
		DCORRPSTCD CHAR(10),
		PLACEOFINC CHAR(30),
		DORMANT CHAR(1),
		STATE CHAR(20),
		SETTACTYPE CHAR(3),
		SETTBANKBR CHAR(40),
		PARACGRPCD CHAR(5)
	)

	INSERT INTO #IFCLIENT
	(
		COMPANYID,
		BRANCHID,
		EAFID,
		ACCTNO,
		ACCTSBNO,
		ACCTGRPCD,
		ACCTTYPECD,
		OFFICERCD,
		SUSPDREASN,
		CLOSEREASN,
		ACCLASSCD,
		CORRMTHD,
		FINANCECD,
		LGLSTAT,
		ACCTFNAME,
		ACCTSNAME,
		CORRADDR1,
		CORRADDR2,
		CORRADDR3,
		CORRADDR4,
		CORRADDR5,
		CORRNAME,
		CORRTITLE,
		CORRPOSTCD,
		FORADDR,
		PHONE,
		PHONE1,
		PHONE2,
		FAX,
		ELECADDR,
		ACCTSTAT,
		DTACCTOPEN,
		DTSUSPND,
		DTCLOSED,
		USROPENED,
		USRSUSPND,
		USRCLOSED,
		FRNACHLDR,
		JNTACHLDR,
		REMARK1,
		REMARK2,
		CUSTTYPE,
		BUMISTAT,
		LSTTRXDT,
		LSTTRDDT,
		BNKRUPTST,
		PRTSTMT,
		DTPRTSTMT,
		DTSTMTPRTD,
		USRCREATED,
		DTCREATED,
		TMCREATED,
		USRUPDATED,
		DTUPDATED,
		TMUPDATED,
		RCDSTAT,
		RCDVERSION,
		PGMLSTUPD,
		TRIGGERACT,
		USRAPPROVE,
		DTAPPROVED,
		TMAPPROVED,
		SERIALNMBR,
		ACTITLE,
		SETTMODECD,
		SETTCURR,
		SETTBANK,
		SETTBANKAC,
		SETTACCTNM,
		ACCESSLVL,
		CRDRANKCD,
		GRPPRFID,
		ACCTUSECD,
		ANALCD1,
		ANALCD2,
		ANALCD3,
		SWIFTADD,
		RELACCTNO,
		CUSTKEY,
		APPFORM,
		AUTOPAYAPP,
		AUTORECAPP,
		ISLFINANCD,
		INETMAIL,
		DCORRADDR1,
		DCORRADDR2,
		DCORRADDR3,
		DCORRADDR4,
		DCORRADDR5,
		DCORRNAME,
		DCORRTITLE,
		DCORRPSTCD,
		PLACEOFINC,
		DORMANT,
		STATE,
		SETTACTYPE,
		SETTBANKBR,
		PARACGRPCD
	)
	SELECT 
	   '',
	   ACCOUNT.[CDSACOpenBranch (selectsource-4)],
	   '',
	   ACCOUNT.[AccountNumber (textinput-5)],
	   '',
	   ACCOUNT.[AccountGroup (selectsource-2)],
	   '',
	   '',
	   ACCOUNT.[SuspensionCloseReason (selectsource-30)],
	   '',--10

	   '',
	   '',
	   '',
	   '',
	   CUSTOMER.[FirstName (textinput-150)],--ACCTFNAME
	   '',
	   CUSTOMER.[Address1 (textinput-35)],
	   CUSTOMER.[Address2 (textinput-36)],
	   CUSTOMER.[Address3 (textinput-37)],
	   CUSTOMER.[State (selectsource-25)],--20

	   CUSTOMER.[Country (selectsource-24)],
	   '',
	   '',
	   '',
	   '',
	   CUSTOMER.[PhoneHouse (textinput-55)], --PHONE
	   CUSTOMER.[PhoneMobile (textinput-57)], --PHONE1
	   '', --PHONE2
	   '',
	   '',--30
	   CUSTOMER.[Startdate (dateinput-16)], --ACCTSTATE
	   CUSTOMER.CreatedTime, --OPENDATE
	   '',
	   CUSTOMER.[Enddate (dateinput-17)],
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',--40
	   '',
	   '',
	   CUSTOMER.[BumiputraStatus (multipleradiosinline-1)], --BUMISTAT
	   '', --LSTTRXDT
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',--50
	   '',
	   '',
	   '',
	   CUSTOMER.UpdatedTime, -- DTUPDATED
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',--60
	   '',
	   '',
	   '',
	   '',
	   ACCOUNT.[SettlementMode (selectbasic-41)],
	   '',
	   '',
	   '',
	   ACCOUNT.[AccountNumber (textinput-5)],--SETTACCTNM
	   '',--70

	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',--80
	   '',
	   '',
	   '',
	   CUSTOMER.[Email (textinput-58)],--INETMAIL
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',--90
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   '',
	   ACCOUNT.[ParentGroup (selectsource-3)]
	FROM 
		CQBTEMPDB.EXPORT.TB_FORMDATA_1410 CUSTOMER
	INNER JOIN
		CQBTempDB.export.Tb_FormData_1409 ACCOUNT ON CUSTOMER.[CustomerID (textinput-1)] = ACCOUNT.[CustomerID (selectsource-1)]

	-- RESULT SET

	SELECT 
		COMPANYID + BRANCHID + EAFID + ACCTNO + ACCTSBNO + ACCTGRPCD + ACCTTYPECD + OFFICERCD + SUSPDREASN + CLOSEREASN +
		ACCLASSCD + CORRMTHD + FINANCECD + LGLSTAT + ACCTFNAME + ACCTSNAME + CORRADDR1 + CORRADDR2 + CORRADDR3 + CORRADDR4 +
		CORRADDR5 + CORRNAME + CORRTITLE + CORRPOSTCD + FORADDR + PHONE + PHONE1 + PHONE2 + FAX + ELECADDR + ACCTSTAT +
		DTACCTOPEN + DTSUSPND + DTCLOSED + USROPENED + USRSUSPND + USRCLOSED + FRNACHLDR + JNTACHLDR + REMARK1 + REMARK2 +
		CUSTTYPE + BUMISTAT + LSTTRXDT + LSTTRDDT + BNKRUPTST + PRTSTMT + DTPRTSTMT + DTSTMTPRTD + USRCREATED + DTCREATED +
		TMCREATED + USRUPDATED + DTUPDATED + TMUPDATED + RCDSTAT + CAST(RCDVERSION AS CHAR(8)) + PGMLSTUPD + TRIGGERACT + USRAPPROVE +
		DTAPPROVED + TMAPPROVED + CAST(SERIALNMBR AS CHAR(8)) + ACTITLE + SETTMODECD + SETTCURR + SETTBANK + SETTBANKAC + SETTACCTNM +
		ACCESSLVL + CRDRANKCD + GRPPRFID + ACCTUSECD + ANALCD1 + ANALCD2 + ANALCD3 + SWIFTADD + RELACCTNO + CUSTKEY +
		APPFORM + AUTOPAYAPP + AUTORECAPP + ISLFINANCD + INETMAIL + DCORRADDR1 + DCORRADDR2 + DCORRADDR3 + DCORRADDR4 +
		DCORRADDR5 + DCORRNAME + DCORRTITLE + DCORRPSTCD + PLACEOFINC + DORMANT + STATE + SETTACTYPE + SETTBANKBR 
	FROM #IFCLIENT

	DROP TABLE #IFCLIENT
END