/****** Object:  Procedure [export].[USP_FRA_IFCOUNTRY]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [export].[USP_FRA_IFCOUNTRY]
(
	@idteProcessDate DATE
)
AS
BEGIN

	SET NOCOUNT ON;

CREATE TABLE #IFCOUNTRY
(
	COUNTRYCD CHAR(3),
	CURRCODE CHAR(3),
	DESCRIPTN CHAR(30),
	ISOCOUNTRY CHAR(2),
	NATIONLTCD CHAR(3),
	COUNTRYFAX CHAR(2),
	USRCREATED CHAR(10),
	DTCREATED DATE,
	TMCREATED CHAR(8),
	USRUPDATED CHAR(10),
	DTUPDATED DATE,
	TMUPDATED CHAR(8),
	PGMLSTUPD CHAR(10),
	RCDSTAT CHAR(1),
	RCDVERSION DECIMAL(5,0),
	TRIGGERACT CHAR(1)
)

	INSERT INTO #IFCOUNTRY
	(
		COUNTRYCD,
		CURRCODE,
		DESCRIPTN,
		ISOCOUNTRY,
		NATIONLTCD,
		COUNTRYFAX,
		USRCREATED,
		DTCREATED,
		TMCREATED,
		USRUPDATED,
		DTUPDATED,
		TMUPDATED,
		PGMLSTUPD,
		RCDSTAT,
		RCDVERSION,
		TRIGGERACT
	)
	SELECT 
		COUNTRY.CountryCd,
		'',
		COUNTRY.TaxDesc,
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		''
	FROM GlobalBO.[setup].[Tb_Country] COUNTRY

	-- RESULT SET

	SELECT 
		COUNTRYCD + CURRCODE + DESCRIPTN + ISOCOUNTRY + NATIONLTCD + COUNTRYFAX + USRCREATED + DTCREATED + TMCREATED +
		USRUPDATED + DTUPDATED + TMUPDATED + PGMLSTUPD + RCDSTAT + CAST(RCDVERSION AS CHAR(8)) + TRIGGERACT
	FROM #IFCOUNTRY

	DROP TABLE #IFCOUNTRY

END