/****** Object:  Procedure [export].[USP_FRA_IFCLIENTM]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [export].[USP_FRA_IFCLIENTM] 
(
	@idteProcessDate DATE
)
AS
BEGIN

	SET NOCOUNT ON;

	CREATE TABLE #IFCLIENTM
	(
		COMPANYID CHAR(1),
		BRANCHID CHAR(4),
		EAFID CHAR(3),
		ACCTNO CHAR(10),
		ACCTSBNO CHAR(4),
		KEYCD CHAR(10),
		MRGREASON CHAR(4),
		DTSTART DATE,
		DTEND DATE,
		AVGAPPMOF DECIMAL(5,2),
		MGNAPPMOF DECIMAL(5,2),
		PRCAPPMOF DECIMAL(5,2),
		CALLMGN DECIMAL(5,2),
		CALLTOLFCT DECIMAL(5,2),
		WDWTOLFCT DECIMAL(5,2),
		ERMTOLFCT DECIMAL(5,2),
		CURRMGN DECIMAL(5,2),
		KLSEMGN DECIMAL(5,2),
		MGNSTATUS CHAR(1),
		DTMGNVIOL DATE,
		MGNCALLSTT CHAR(1),
		DTCALLISSF DATE,
		DTCALLISSL DATE,
		TRDACBAL DECIMAL(15,2),
		CSHACBAL DECIMAL(15,2),
		SHRHLDVAL DECIMAL(15,2),
		FDHLDVAL DECIMAL(15,2),
		COLHLDVAL DECIMAL(15,2),
		SHRMGNVAL DECIMAL(15,2),
		FDMGNVAL DECIMAL(15,2),
		COLMGNVAL DECIMAL(15,2),
		CALLNTVL DECIMAL(15,2),
		TRDLIMT DECIMAL(15,2),
		CSHTOPUP DECIMAL(15,2),
		COLTOPUP DECIMAL(15,2),
		FORCESELL DECIMAL(15,2),

		DTMGNRESLV DATE,
		AVAILFUND DECIMAL(15,2),
		TOTCOLLVAL DECIMAL(15,2),
		TOTMGNBVAL DECIMAL(15,2),
		LASTRODATE DATE,
		NEXTRODATE DATE,
		RLOVRRTCD CHAR(3),
		USRCREATED CHAR(10),
		DTCREATED DATE,
		TMCREATED CHAR(8),
		USRUPDATED CHAR(10),
		DTUPDATED DATE,
		TMUPDATED CHAR(8),
		RCDSTAT CHAR(1),
		RCDVERSION DECIMAL(5,0),

		PGMLSTUPD CHAR(10),
		TRIGGERACT CHAR(1),
		APPROVELIM DECIMAL(15,2),
		CURCOMFEE DECIMAL(14,2),
		COMFEECD CHAR(3),

		DATE1 DATE,
		DATE2 DATE,
		DATE3 DATE,

		AMOUNT2 DECIMAL(15,2),
		AMOUNT3 DECIMAL(15,2),
		TEXT1 CHAR(10),
		TEXT2 CHAR(10),
		TEXT3 CHAR(10),

		AMOUNT1 DECIMAL(15,2),
		MGNOFFDT DATE,
		MAXMOF DECIMAL(5,2),
		MNMOF DECIMAL(5,2),
		MAXAMTTRX DECIMAL(15,2),
		AAMFD DECIMAL(5,2),
		MGNROFFDT DATE,
		MGNAGRDT DATE,
		INTCODE CHAR(3),
		INTCODE1 CHAR(3),
		DLRROLRATE DECIMAL(5,2),
		CURCRINT DECIMAL(15,2),
		CURDRINT DECIMAL(15,2),
		COFCODE CHAR(3),
		DTINTCOMP DATE,
		RENEWCODE CHAR(3),
		SRVCODE1 CHAR(3),
		SRVCODE2 CHAR(3),
		COMFEEDT DATE,
		PRVLSTRODT DATE,
		CALLCOUNT DECIMAL(9,0),
		AGEBREACH DECIMAL(9,0),
		SALIMT DECIMAL(15,2),
		LOFDATE DATE,
		FACLDATE DATE,
		MOADATE DATE,
		POADATE DATE
	)

	INSERT INTO #IFCLIENTM
	(
		COMPANYID,
		BRANCHID,
		EAFID,
		ACCTNO,
		ACCTSBNO,
		KEYCD,
		MRGREASON,
		DTSTART,
		DTEND,
		AVGAPPMOF,
		MGNAPPMOF,
		PRCAPPMOF,
		CALLMGN,
		CALLTOLFCT,
		WDWTOLFCT,
		ERMTOLFCT,
		CURRMGN,
		KLSEMGN,
		MGNSTATUS,
		DTMGNVIOL,
		MGNCALLSTT,
		DTCALLISSF,
		DTCALLISSL,
		TRDACBAL,
		CSHACBAL,
		SHRHLDVAL,
		FDHLDVAL,
		COLHLDVAL,
		SHRMGNVAL,
		FDMGNVAL,
		COLMGNVAL,
		CALLNTVL,
		TRDLIMT,
		CSHTOPUP,
		COLTOPUP,
		FORCESELL,
		DTMGNRESLV,
		AVAILFUND,
		TOTCOLLVAL,
		TOTMGNBVAL,
		LASTRODATE,
		NEXTRODATE,
		RLOVRRTCD,
		USRCREATED,
		DTCREATED,
		TMCREATED,
		USRUPDATED,
		DTUPDATED,
		TMUPDATED,
		RCDSTAT,
		RCDVERSION,
		PGMLSTUPD,
		TRIGGERACT,
		APPROVELIM,
		CURCOMFEE,
		COMFEECD,
		DATE1,
		DATE2,
		DATE3,
		AMOUNT2,
		AMOUNT3,
		TEXT1,
		TEXT2,
		TEXT3,
		AMOUNT1,
		MGNOFFDT,
		MAXMOF,
		MNMOF,
		MAXAMTTRX,
		AAMFD,
		MGNROFFDT,
		MGNAGRDT,
		INTCODE,
		INTCODE1,
		DLRROLRATE,
		CURCRINT,
		CURDRINT,
		COFCODE,
		DTINTCOMP,
		RENEWCODE,
		SRVCODE1,
		SRVCODE2,
		COMFEEDT,
		PRVLSTRODT,
		CALLCOUNT,
		AGEBREACH,
		SALIMT,
		LOFDATE,
		FACLDATE,
		MOADATE,
		POADATE
	)
	SELECT 
		'',
		ACCOUNT.[CDSACOpenBranch (selectsource-4)],
		'',
		ACCOUNT.[AccountNumber (textinput-5)],
		'',
		'',
		'',
		'',
		ACCOUNT.[TenorExpiryDate (dateinput-5)], --DTEND
		[ApprovedRSV (textinput-43)], --AVGAPPMOF

		'',
		ACCOUNT.[PriceCapMOF (textinput-44)],
		'',--CALLMGN
		'',
		'',
		'',
		'',
		[CurrentRSV (textinput-48)],--KLSEMGN
		'',
		'',--20

		'',
		'',
		'',
		RPT.CashBalance,--TRDACBAL
		'',
		'',
		'',
		'',
		'',
		'',--30

		'',
		'',
		ACCOUNT.[AvailableTradingLimit (textinput-55)],--TRDLIMT
		'',
		'',
		'',
		'',
		'',
		'',
		'',--40

		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',--50

		'',
		'',
		'',
		ACCOUNT.[ApproveTradingLimit (textinput-54)],
		'',
		'',
		'',
		'',
		'',
		'',--60

		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',--70

		'',
		'',
		'',
		'',
		'',
		'',
		'',--CURDRINT
		'',
		'',
		'',--80

		'',
		'',
		'',
		'',
		'',--CALLCOUNT
		'',
		'',
		'',
		'',
		'',--90

		''
	FROM 
		CQBTempDB.export.Tb_FormData_1409 ACCOUNT
	INNER JOIN 
		GLOBALBORPT.valuation.Tb_CashRPValuationCollateralRpt RPT ON ACCOUNT.[AccountNumber (textinput-5)] = RPT.AcctNo
		
	--RESULT SET 

	SELECT
		COMPANYID + BRANCHID + EAFID + ACCTNO + ACCTSBNO + KEYCD + MRGREASON + DTSTART + DTEND + CAST(AVGAPPMOF AS CHAR(8)) + CAST(MGNAPPMOF AS CHAR(8)) +
		CAST(PRCAPPMOF AS CHAR(8)) + CAST(CALLMGN AS CHAR(8)) + CAST(CALLTOLFCT AS CHAR(8)) + CAST(WDWTOLFCT AS CHAR(8)) + CAST(ERMTOLFCT AS CHAR(8)) 
		+ CAST(CURRMGN AS CHAR(8)) + CAST(KLSEMGN AS CHAR(8)) + MGNSTATUS + DTMGNVIOL + MGNCALLSTT + DTCALLISSF + DTCALLISSL + CAST(TRDACBAL AS CHAR(8)) 
		+ CAST(CSHACBAL AS CHAR(8)) + CAST(SHRHLDVAL AS CHAR(8)) + CAST(FDHLDVAL AS CHAR(8)) + CAST(COLHLDVAL AS CHAR(8)) + CAST(SHRMGNVAL AS CHAR(8)) 
		+ CAST(FDMGNVAL AS CHAR(8)) + CAST(COLMGNVAL AS CHAR(8)) + CAST(CALLNTVL AS CHAR(8)) + CAST(TRDLIMT AS CHAR(8)) + CAST(CSHTOPUP AS CHAR(8)) 
		+ CAST(COLTOPUP AS CHAR(8)) + CAST(FORCESELL AS CHAR(8)) + DTMGNRESLV + CAST(AVAILFUND AS CHAR(8)) + CAST(TOTCOLLVAL AS CHAR(8)) 
		+ CAST(TOTMGNBVAL AS CHAR(8)) + LASTRODATE + NEXTRODATE + RLOVRRTCD + USRCREATED + DTCREATED + TMCREATED + USRUPDATED + DTUPDATED + TMUPDATED 
		+ RCDSTAT + CAST(RCDVERSION AS CHAR(8)) + PGMLSTUPD + TRIGGERACT + CAST(APPROVELIM AS CHAR(8)) + CAST(CURCOMFEE AS CHAR(8)) + COMFEECD + DATE1 
		+ DATE2 + DATE3 + CAST(AMOUNT2 AS CHAR(8)) + CAST(AMOUNT3 AS CHAR(8)) + TEXT1 + TEXT2 + TEXT3 + CAST(AMOUNT1 AS CHAR(8)) + MGNOFFDT 
		+ CAST(MAXMOF AS CHAR(8)) + CAST(MNMOF AS CHAR(8)) + CAST(MAXAMTTRX AS CHAR(8)) + CAST(AAMFD AS CHAR(8)) + MGNROFFDT + MGNAGRDT + INTCODE 
		+ INTCODE1 + CAST(DLRROLRATE AS CHAR(8)) + CAST(CURCRINT AS CHAR(8)) + CAST(CURDRINT AS CHAR(8)) + COFCODE + DTINTCOMP + RENEWCODE + SRVCODE1 
		+ SRVCODE2 + COMFEEDT + PRVLSTRODT + CAST(CALLCOUNT AS CHAR(8)) + CAST(AGEBREACH AS CHAR(8)) + CAST(SALIMT AS CHAR(8)) + LOFDATE + FACLDATE 
		+ MOADATE + POADATE
	FROM #IFCLIENTM

	DROP TABLE #IFCLIENTM

END