/****** Object:  Table [import].[Tb_Introducer]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [import].[Tb_Introducer](
	[INTRODCCD] [varchar](10) NOT NULL,
	[INTRODCNM1] [varchar](60) NOT NULL,
	[INTRODCNM2] [varchar](60) NOT NULL,
	[INTRODCTTL] [varchar](20) NOT NULL,
	[CORRADDR1] [varchar](40) NOT NULL,
	[CORRADDR2] [varchar](40) NOT NULL,
	[CORRADDR3] [varchar](40) NOT NULL,
	[CORRADDR4] [varchar](40) NOT NULL,
	[CORRPOSTCD] [varchar](10) NOT NULL,
	[PHONE] [varchar](15) NOT NULL,
	[PHONE1] [varchar](15) NOT NULL,
	[PHONE2] [varchar](15) NOT NULL,
	[FAX] [varchar](15) NOT NULL,
	[INETMAIL] [varchar](50) NOT NULL,
	[INTROCHGCD] [char](3) NOT NULL,
	[PROFTSHRCD] [char](3) NOT NULL,
	[BRKGSHRCD] [char](3) NOT NULL,
	[INTROTYPE] [char](1) NOT NULL,
	[COMPANYID] [char](1) NOT NULL,
	[BRANCHID] [char](4) NOT NULL,
	[EAFID] [char](3) NOT NULL,
	[ACCTNO] [varchar](10) NOT NULL,
	[ACCTSBNO] [char](4) NOT NULL,
	[BROKERCD] [char](5) NOT NULL,
	[DLREAFID] [char](3) NOT NULL,
	[DEALERCD] [char](4) NOT NULL,
	[SRVRTCD1] [char](3) NOT NULL,
	[SRVRTCD2] [char](3) NOT NULL,
	[IND1] [char](1) NOT NULL,
	[IND2] [char](1) NOT NULL,
	[IND3] [char](1) NOT NULL,
	[TEXT1] [varchar](10) NOT NULL,
	[TEXT2] [varchar](10) NOT NULL,
	[TEXT3] [varchar](10) NOT NULL,
	[USRCREATED] [varchar](10) NOT NULL,
	[DTCREATED] [varchar](10) NOT NULL,
	[TMCREATED] [varchar](8) NOT NULL,
	[USRUPDATED] [varchar](10) NOT NULL,
	[DTUPDATED] [varchar](10) NOT NULL,
	[TMUPDATED] [varchar](8) NOT NULL
) ON [PRIMARY]